extends Node

## High-level network manager providing protobuf-aware messaging.
## Wraps TcpConnection with Msg/MsgRsp serialization and reconnection logic.
##
## Usage:
##   1. Add as Autoload singleton named "Net" in Project Settings
##   2. Net.connect_to_server("127.0.0.1", 9501)
##   3. Net.send_message(Proto.MsgType.MsgType_Login, login_request)
##   4. Connect to signals: msg_received, connection_state_changed, etc.

signal connection_state_changed(state: int)
signal msg_received(msg_type: int, err_code: int, payload_bytes: PackedByteArray)

const Proto = preload("res://proto_gen/msg.gd")
const TcpConn = preload("res://scripts/network/tcp_connection.gd")

enum ConnState { DISCONNECTED = 0, CONNECTING = 1, CONNECTED = 2 }

var _connection
var _reconnect_enabled: bool = false
var _reconnect_timer: float = 0.0
var _reconnect_interval: float = 3.0
var _host: String
var _port: int

func _ready() -> void:
	_connection = TcpConn.new()
	_connection.connected.connect(_on_connected)
	_connection.disconnected.connect(_on_disconnected)
	_connection.message_received.connect(_on_raw_message)

func _process(delta: float) -> void:
	if _connection == null:
		return
	_connection.poll()

	if _reconnect_enabled and _connection.get_state() == TcpConn.State.DISCONNECTED:
		_reconnect_timer -= delta
		if _reconnect_timer <= 0:
			_reconnect_timer = _reconnect_interval
			print("[Net] Reconnecting to %s:%d ..." % [_host, _port])
			_connection.connect_to_server(_host, _port)

func get_state() -> int:
	return _connection.get_state()

func is_connected_to_server() -> bool:
	return _connection.get_state() == TcpConn.State.CONNECTED

# --- Connection API ---

func connect_to_server(host: String, port: int, auto_reconnect: bool = false) -> Error:
	_host = host
	_port = port
	_reconnect_enabled = auto_reconnect
	_reconnect_timer = 0.0
	return _connection.connect_to_server(host, port)

func disconnect_from_server() -> void:
	_reconnect_enabled = false
	_connection.disconnect_from_server()

# --- Messaging API ---

## Build a Msg (client→server), serialize, and send.
## `payload` should be a protobuf message object with a to_bytes() method,
## or null for messages with no payload.
func send_message(msg_type: int, payload = null) -> Error:
	var msg = Proto.Msg.new()
	var head = msg.new_head()
	head.set_type(msg_type)

	if payload != null:
		var payload_bytes: PackedByteArray = payload.to_bytes()
		var any = msg.new_payload()
		any.set_type_url(_type_url_for(msg_type))
		any.set_value(payload_bytes)

	var data := msg.to_bytes()
	return _connection.send_data(data)

# --- Internals ---

func _on_connected() -> void:
	_reconnect_timer = 0.0
	print("[Net] Connected to %s:%d" % [_host, _port])
	connection_state_changed.emit(ConnState.CONNECTED)

func _on_disconnected() -> void:
	print("[Net] Disconnected")
	connection_state_changed.emit(ConnState.DISCONNECTED)

func _on_raw_message(data: PackedByteArray) -> void:
	var rsp = Proto.MsgRsp.new()
	var result = rsp.from_bytes(data)
	if result != Proto.PB_ERR.NO_ERRORS:
		push_error("[Net] Failed to parse MsgRsp, error: %d" % result)
		return

	var msg_type: int = rsp.get_head().get_type()
	var err_code: int = rsp.get_head().get_res()
	var payload_bytes := PackedByteArray()
	if rsp.has_payload() and rsp.get_payload().has_value():
		payload_bytes = rsp.get_payload().get_value()

	msg_received.emit(msg_type, err_code, payload_bytes)

## Map MsgType enum to the type_url used in Any.
## Must match the format generated by C++ protobuf's Any::PackFrom():
## "type.googleapis.com/<package>.<MessageName>"
## The server's UnpackTo() validates this prefix.
static func _type_url_for(msg_type: int) -> String:
	const PREFIX = "type.googleapis.com/MyGame."
	match msg_type:
		Proto.MsgType.MsgType_Login:
			return PREFIX + "RequestLogin"
		Proto.MsgType.MsgType_Logout:
			return PREFIX + "RequestLogout"
		Proto.MsgType.MsgType_Act:
			return PREFIX + "RequestAct"
		Proto.MsgType.MsgType_HeartBeat:
			return PREFIX + "RequestHeartBeat"
		_:
			return PREFIX + "Unknown"
